# convert the master docx to a markdown that can be hand edited to clean up
# pandoc -f docx -t markdown BringYour\ Privacy\ Policy\ -\ v1.docx -o export2/privacyout.md

# convert the markdown to a clean html
# pandoc -f markdown -t html terms.md -o out/terms.html

