
# import babel.languages
# import pycountry
import re
import os


countries = {
    "ad": "Andorra",
"ae": "United Arab Emirates",
"af": "Afghanistan",
"ag": "Antigua and Barbuda",
"ai": "Anguilla",
"al": "Albania",
"am": "Armenia",
"ao": "Angola",
"aq": "Antarctica",
"ar": "Argentina",
"as": "American Samoa",
"at": "Austria",
"au": "Australia",
"aw": "Aruba",
"ax": "\xC5land Islands",
"az": "Azerbaijan",
"ba": "Bosnia and Herzegovina",
"bb": "Barbados",
"bd": "Bangladesh",
"be": "Belgium",
"bf": "Burkina Faso",
"bg": "Bulgaria",
"bh": "Bahrain",
"bi": "Burundi",
"bj": "Benin",
"bl": "Saint Barth\xE9lemy",
"bm": "Bermuda",
"bn": "Brunei Darussalam",
"bo": "Bolivia",
"bq": "Bonaire, Sint Eustatius and Saba",
"br": "Brazil",
"bs": "Bahamas",
"bt": "Bhutan",
"bv": "Bouvet Island",
"bw": "Botswana",
"by": "Belarus",
"bz": "Belize",
"ca": "Canada",
"cc": "Cocos (Keeling) Islands",
"cd": "Democratic Republic of the Congo",
"cf": "Central African Republic",
"cg": "Congo",
"ch": "Switzerland",
"ci": "C\xF4te d'Ivoire",
"ck": "Cook Islands",
"cl": "Chile",
"cm": "Cameroon",
"cn": "China",
"co": "Colombia",
"cr": "Costa Rica",
"cu": "Cuba",
"cv": "Capo Verde",
"cw": "Cura\xE7ao",
"cx": "Christmas Island",
"cy": "Cyprus",
"cz": "Czechia",
"de": "Germany",
"dj": "Djibouti",
"dk": "Denmark",
"dm": "Dominica",
"do": "Dominican Republic",
"dz": "Algeria",
"ec": "Ecuador",
"ee": "Estonia",
"eg": "Egypt",
"eh": "Western Sahara",
"er": "Eritrea",
"es": "Spain",
"et": "Ethiopia",
"fi": "Finland",
"fj": "Fiji",
"fk": "Falkland Islands (Malvinas)",
"fm": "Micronesia",
"fo": "Faroe Islands",
"fr": "France",
"ga": "Gabon",
"gb": "United Kingdom",
"gd": "Grenada",
"ge": "Georgia",
"gf": "French Guiana",
"gg": "Guernsey",
"gh": "Ghana",
"gi": "Gibraltar",
"gl": "Greenland",
"gm": "Gambia",
"gn": "Guinea",
"gp": "Guadeloupe",
"gq": "Equatorial Guinea",
"gr": "Greece",
"gs": "South Georgia and the South Sandwich Islands",
"gt": "Guatemala",
"gu": "Guam",
"gw": "Guinea-Bissau",
"gy": "Guyana",
"hk": "Hong Kong",
"hm": "Heard Island and McDonald Islands",
"hn": "Honduras",
"hr": "Croatia",
"ht": "Haiti",
"hu": "Hungary",
"id": "Indonesia",
"ie": "Ireland",
"il": "Israel",
"im": "Isle of Man",
"in": "India",
"io": "British Indian Ocean Territory",
"iq": "Iraq",
"ir": "Iran",
"is": "Iceland",
"it": "Italy",
"je": "Jersey",
"jm": "Jamaica",
"jo": "Jordan",
"jp": "Japan",
"ke": "Kenya",
"kg": "Kyrgyzstan",
"kh": "Cambodia",
"ki": "Kiribati",
"km": "Comoros",
"kn": "Saint Kitts and Nevis",
"kp": "North Korea",
"kr": "South Korea",
"kw": "Kuwait",
"ky": "Cayman Islands",
"kz": "Kazakhstan",
"la": "Lao People's Democratic Republic",
"lb": "Lebanon",
"lc": "Saint Lucia",
"li": "Liechtenstein",
"lk": "Sri Lanka",
"lr": "Liberia",
"ls": "Lesotho",
"lt": "Lithuania",
"lu": "Luxembourg",
"lv": "Latvia",
"ly": "Libya",
"ma": "Morocco",
"mc": "Monaco",
"md": "Moldova",
"me": "Montenegro",
"mf": "Saint Martin (French part)",
"mg": "Madagascar",
"mh": "Marshall Islands",
"mk": "North Macedonia",
"ml": "Mali",
"mm": "Myanmar",
"mn": "Mongolia",
"mo": "Macao",
"mp": "Northern Mariana Islands",
"mq": "Martinique",
"mr": "Mauritania",
"ms": "Montserrat",
"mt": "Malta",
"mu": "Mauritius",
"mv": "Maldives",
"mw": "Malawi",
"mx": "Mexico",
"my": "Malaysia",
"mz": "Mozambique",
"na": "Namibia",
"nc": "New Caledonia",
"ne": "Niger",
"nf": "Norfolk Island",
"ng": "Nigeria",
"ni": "Nicaragua",
"nl": "Netherlands",
"no": "Norway",
"np": "Nepal",
"nr": "Nauru",
"nu": "Niue",
"nz": "New Zealand",
"om": "Oman",
"pa": "Panama",
"pe": "Peru",
"pf": "French Polynesia",
"pg": "Papua New Guinea",
"ph": "Philippines",
"pk": "Pakistan",
"pl": "Poland",
"pm": "Saint Pierre and Miquelon",
"pn": "Pitcairn",
"pr": "Puerto Rico",
"ps": "Palestine",
"pt": "Portugal",
"pw": "Palau",
"py": "Paraguay",
"qa": "Qatar",
"re": "R\xE9union",
"ro": "Romania",
"rs": "Serbia",
"ru": "Russia",
"rw": "Rwanda",
"sa": "Saudi Arabia",
"sb": "Solomon Islands",
"sc": "Seychelles",
"sd": "Sudan",
"se": "Sweden",
"sg": "Singapore",
"sh": "Saint Helena, Ascension and Tristan da Cunha",
"si": "Slovenia",
"sj": "Svalbard and Jan Mayen",
"sk": "Slovakia",
"sl": "Sierra Leone",
"sm": "San Marino",
"sn": "Senegal",
"so": "Somalia",
"sr": "Suriname",
"ss": "South Sudan",
"st": "Sao Tome and Principe",
"sv": "El Salvador",
"sx": "Sint Maarten (Dutch part)",
"sy": "Syrian Arab Republic",
"sz": "Eswatini",
"tc": "Turks and Caicos Islands",
"td": "Chad",
"tf": "French Southern Territories",
"tg": "Togo",
"th": "Thailand",
"tj": "Tajikistan",
"tk": "Tokelau",
"tl": "Timor-Leste",
"tm": "Turkmenistan",
"tn": "Tunisia",
"to": "Tonga",
"tr": "Turkey",
"tt": "Trinidad and Tobago",
"tv": "Tuvalu",
"tw": "Taiwan",
"tz": "Tanzania",
"ua": "Ukraine",
"ug": "Uganda",
"uk": "United Kingdom",
"um": "United States Minor Outlying Islands",
"us": "United States",
"uy": "Uruguay",
"uz": "Uzbekistan",
"va": "Vatican City",
"vc": "Saint Vincent and the Grenadines",
"ve": "Venezuela",
"vg": "British Virgin Islands",
"vi": "U.S. Virgin Islands",
"vn": "Vietnam",
"vu": "Vanuatu",
"wf": "Wallis and Futuna",
"ws": "Samoa",
"ye": "Yemen",
"yt": "Mayotte",
"za": "South Africa",
"zm": "Zambia",
"zw": "Zimbabwe",
"xk": "Kosovo",
}

# gemini
# for each of the following language codes, 
# print up to 5 2-letter country codes where the language is most used. 
# Format as a python map to list lowercase.
language_code_country_codes = {
    'aa': ['dj', 'er'],
    'ab': ['ge'],
    'ace': ['id'],
    'ady': ['ru'],
    'af': ['za', 'na'],
    'ak': ['gh'],
    'als': ['al'],
    'alt': ['ru'],
    'ami': ['tw'],
    'am': ['et'],
    'ang': [],  # Extinct language
    'ann': ['ng'],
    'anp': ['in'],
    'an': ['es'],
    'arc': ['iq'],
    'ar': ['eg', 'sa', 'dz', 'iq', 'ma'],
    'ary': ['ma'],
    'arz': ['eg'],
    'ast': ['es'],
    'as': ['in'],
    'atj': ['ca'],
    'avk': ['ru'],
    'av': ['ru'],
    'awa': ['in'],
    'ay': ['bo'],
    'azb': ['ir'],
    'az': ['az'],
    'ban': ['id'],
    'bar': ['at'],
    'ba': ['ru'],
    'bbc': ['id'],
    'bcl': ['ph'],
    'bdr': ['id'],
    'be': ['by'],
    'bew': ['id'],
    'bg': ['bg'],
    'bh': ['in'],
    'bi': ['vu'],
    'bjn': ['id'],
    'blk': ['la'],
    'bm': ['ml'],
    'bn': ['bd', 'in'],
    'bo': ['cn'],
    'bpy': ['bd'],
    'br': ['fr'],
    'bs': ['ba'],
    'btm': ['id'],
    'bug': ['id'],
    'bxr': ['cn'],
    'ca': ['es', 'ad'],
    'cdo': ['cn'],
    'ceb': ['ph'],
    'ce': ['ru'],
    'cho': ['us'],
    'chr': ['us'],
    'ch': ['gu'],
    'chy': ['us'],
    'ckb': ['iq'],
    'co': ['fr', 'it', 'es'],
    'crh': ['ua'],
    'cr': ['ca'],
    'csb': ['pl'],
    'cs': ['cz', 'sk'],
    'cu': ['ru'],
    'cv': ['ru'],
    'cy': ['gb'],
    'dag': ['gh'],
    'da': ['dk', 'gl'],
    'de': ['de', 'at', 'ch', 'be', 'lu'],
    'dga': ['gh'],
    'din': ['sd', 'ss'],
    'diq': ['tr'],
    'dk': ['cm'],
    'dsb': ['de'],
    'dtp': ['id'],
    'dty': ['np'],
    'dv': ['mv'],
    'dz': ['bt'],
    'ee': ['gh', 'tg'],
    'el': ['gr', 'cy'],
    'eml': ['it'],
    'en': ['us', 'gb', 'ca', 'au', 'nz'],
    'eo': [],  # Constructed language
    'es': ['es', 'mx', 'co', 'ar', 'pe'],
    'et': ['ee'],
    'eu': ['es'],
    'ext': ['es'],
    'fat': ['gw'],
    'fa': ['ir', 'af'],
    'ff': ['sn', 'gn', 'ml', 'mr', 'gm'],
    'fi': ['fi'],
    'fj': ['fj'],
    'fon': ['bj'],
    'fo': ['fo'],
    'frp': ['ch'],
    'frr': ['de'],
    'fr': ['fr', 'ca', 'be', 'ch', 'lu'],
    'fur': ['it'],
    'fy': ['nl'],
    'gag': ['tr'],
    'gan': ['cn'],
    'ga': ['ie'],
    'gcr': ['gf'],
    'gd': ['gb'],
    'glk': ['ir'],
    'gl': ['es'],
    'gn': ['py'],
    'gom': ['in'],
    'gor': ['id'],
    'got': [],  # Extinct language
    'gpe': ['ng'],
    'guc': ['co'],
    'gur': ['gh'],
    'gu': ['in'],
    'guw': ['ng'],
    'gv': ['im'],
    'hak': ['cn'],
    'ha': ['ng'],
    'haw': ['us'],
    'he': ['il'],
    'hif': ['fj'],
    'hi': ['in'],
    'ho': ['pg'],
    'hr': ['hr'],
    'hsb': ['de'],
    'ht': ['ht'],
    'hu': ['hu'],
    'hy': ['am'],
    'hyw': ['am'],
    'hz': ['na'],
    'ia': [],  # Constructed language
    'iba': ['my'],
    'id': ['id'],
    'ie': [],  # Constructed language
    'igl': ['ph'],
    'ig': ['ng'],
    'ii': ['cn'],
    'ik': ['ca'],
    'ilo': ['ph'],
    'inh': ['ru'],
    'io': [],  # Constructed language
    'is': ['is'],
    'it': ['it', 'ch', 'sm', 'va'],
    'iu': ['ca'],
    'jam': ['jm'],
    'ja': ['jp'],
    'jbo': [],  # Constructed language
    'jv': ['id'],
    'kaa': ['uz'],
    'kab': ['dz'],
    'ka': ['ge'],
    'kbd': ['ru'],
    'kbp': ['tg'],
    'kcg': ['ng'],
    'kge': ['au'],
    'kg': ['cg'],
    'ki': ['ke'],
    'kj': ['na'],
    'kk': ['kz'],
    'kl': ['gl'],
    'km': ['kh'],
    'kn': ['in'],
    'koi': ['ru'],
    'ko': ['kr', 'kp'],
    'krc': ['ru'],
    'kr': ['ng'],
    'ksh': ['de'],
    'ks': ['in'],
    'kus': ['sd'],
    'ku': ['iq', 'tr', 'ir', 'sy'],
    'kv': ['ru'],
    'kw': ['gb'],
    'ky': ['kg'],
    'lad': ['il'],
    'la': ['va'],
    'lbe': ['ru'],
    'lb': ['lu'],
    'lez': ['ru'],
    'lfn': [],  # Constructed language
    'lg': ['ug'],
    'lij': ['it'],
    'li': ['nl'],
    'lld': ['it'],
    'lmo': ['it'],
    'ln': ['cd'],
    'lo': ['la'],
    'lrc': ['ir'],
    'ltg': ['lv'],
    'lt': ['lt'],
    'lv': ['lv'],
    'mad': ['id'],
    'mai': ['in'],
    'mdf': ['ru'],
    'mg': ['mg'],
    'mhr': ['ru'],
    'mh': ['mh'],
    'min': ['id'],
    'mi': ['nz'],
    'mk': ['mk'],
    'ml': ['in'],
    'mni': ['in'],
    'mn': ['mn'],
    'mnw': ['mm'],
    'mos': ['bf'],
    'mo': ['md'],
    'mrj': ['ru'],
    'mr': ['in'],
    'ms': ['my', 'bn', 'sg'],
    'mt': ['mt'],
    'mus': ['us'],
    'mwl': ['pt'],
    'myv': ['ru'],
    'my': ['mm'],
    'mzn': ['ir'],
    'nah': ['mx'],
    'nap': ['it'],
    'na': ['nr'],
    'nds': ['de'],
    'ne': ['np'],
    'new': ['np'],
    'ng': ['na'],
    'nia': ['id'],
    'nl': ['nl', 'be'],
    'nn': ['no'],
    'nov': [],  # Constructed language
    'no': ['no'],
    'nqo': [],  # No country code
    'nrm': ['fr'],
    'nr': ['za'],
    'nso': ['za'],
    'nv': ['us'],
    'ny': ['mw'],
    'oc': ['fr', 'es', 'it'],
    'olo': ['ru'],
    'om': ['et', 'ke'],
    'or': ['in'],
    'os': ['ge', 'ru'],
    'pag': ['ph'],
    'pam': ['ph'],
    'pap': ['aw', 'cw'],
    'pa': ['pk', 'in'],
    'pcd': ['fr'],
    'pcm': ['ng'],
    'pdc': ['us'],
    'pfl': ['de'],
    'pih': ['nf'],
    'pi': ['in'],
    'pl': ['pl'],
    'pms': ['it'],
    'pnb': ['pk'],
    'pnt': ['gr'],
    'ps': ['af'],
    'pt': ['pt', 'br', 'ao', 'mz', 'tl'],
    'pwn': ['in'],
    'qu': ['pe', 'bo', 'ec', 'co'],
    'rm': ['ch'],
    'rmy': ['ro'],
    'rn': ['bi'],
    'ro': ['ro', 'md'],
    'rsk': ['cn'],
    'rue': ['ua'],
    'ru': ['ru', 'ua', 'kz', 'by', 'kg'],
    'rw': ['rw'],
    'sah': ['ru'],
    'sat': ['in'],
    'sa': ['in'],
    'scn': ['it'],
    'sco': ['gb'],
    'sc': ['it'],
    'sd': ['pk', 'in'],
    'se': ['no', 'se', 'fi'],
    'sg': ['cf'],
    'shi': ['ma'],
    'shn': ['mm'],
    'sh': ['ba', 'hr', 'me', 'rs'],
    'si': ['lk'],
    'skr': ['pk'],
    'sk': ['sk'],
    'sl': ['si'],
    'smn': ['fi'],
    'sm': ['ws'],
    'sn': ['zw'],
    'so': ['so', 'et', 'ke', 'dj'],
    'sq': ['al', 'mk', 'xk'],
    'srn': ['sr'],
    'sr': ['rs', 'ba', 'me', 'xk'],
    'ss': ['sz', 'za'],
    'stq': ['de'],
    'st': ['ls'],
    'su': ['id'],
    'sv': ['se', 'fi', 'ax'],
    'sw': ['tz', 'ke', 'ug', 'cd', 'rw'],
    'szl': ['pl'],
    'szy': ['et'],
    'ta': ['in', 'lk', 'sg', 'my'],
    'tay': ['ca'],
    'tcy': ['in'],
    'tdd': ['cn'],
    'ten': ['zm'],
    'tet': ['tl'],
    'te': ['in'],
    'tg': ['tj'],
    'th': ['th'],
    'ti': ['er', 'et'],
    'tk': ['tm'],
    'tlh': [],  # Constructed language
    'tl': ['ph'],
    'tly': ['az'],
    'tn': ['bw', 'za'],
    'to': ['to'],
    'tpi': ['pg'],
    'trv': ['tw'],
    'tr': ['tr', 'cy', 'bg'],
    'ts': ['za'],
    'tt': ['ru'],
    'tum': ['mw'],
    'tw': ['gh'],
    'tyv': ['ru'],
    'ty': ['pf'],
    'udm': ['ru'],
    'ug': ['cn'],
    'uk': ['ua'],
    'ur': ['pk', 'in'],
    'uz': ['uz'],
    'vec': ['it'],
    'vep': ['ru'],
    've': ['za'],
    'vi': ['vn'],
    'vls': ['be'],
    'vo': [],  # Constructed language
    'war': ['ph'],
    'wa': ['be'],
    'wo': ['sn'],
    'wuu': ['cn'],
    'xal': ['ru'],
    'xh': ['za'],
    'xmf': ['ge'],
    'yi': ['us'],
    'yo': ['ng'],
    'za': ['za'],
    'zea': ['nl'],
    'zgh': ['ma'],
    'zh': ['cn', 'sg', 'tw', 'my', 'hk'],
    'zu': ['za']
}

country_code_top_sports = {
'ad': ['Football', 'Basketball', 'Cycling'],
'ae': ['Football', 'Cricket', 'Horse Racing'],
'af': ['Cricket', 'Football', 'Buzkashi'],
'ag': ['Cricket', 'Football', 'Athletics'],
'ai': ['Boat Racing', 'Cricket', 'Basketball'],
'al': ['Football', 'Weightlifting', 'Basketball'],
'am': ['Wrestling', 'Football', 'Boxing'],
'ao': ['Football', 'Basketball', 'Roller Hockey'],
'aq': ['N/A'],
'ar': ['Football', 'Basketball', 'Rugby Union'],
'as': ['American Football', 'Volleyball', 'Soccer'],
'at': ['Skiing', 'Football', 'Tennis'],
'au': ['Australian Rules Football', 'Cricket', 'Rugby League'],
'aw': ['Baseball', 'Football', 'Volleyball'],
'ax': ['N/A'],
'az': ['Wrestling', 'Football', 'Judo'],
'ba': ['Football', 'Basketball', 'Volleyball'],
'bb': ['Cricket', 'Football', 'Athletics'],
'bd': ['Cricket', 'Football', 'Kabaddi'],
'be': ['Cycling', 'Football', 'Tennis'],
'bf': ['Football', 'Cycling', 'Basketball'],
'bg': ['Football', 'Volleyball', 'Weightlifting'],
'bh': ['Football', 'Basketball', 'Formula One'],
'bi': ['Football', 'Basketball', 'Athletics'],
'bj': ['Football', 'Basketball', 'Athletics'],
'bl': ['N/A'],
'bm': ['Cricket', 'Football', 'Sailing'],
'bn': ['Football', 'Sepak Takraw', 'Badminton'],
'bo': ['Football', 'Futsal', 'Volleyball'],
'bq': ['N/A'],
'br': ['Football', 'Volleyball', 'Mixed Martial Arts'],
'bs': ['Athletics', 'Basketball', 'Cricket'],
'bt': ['Archery', 'Football', 'Cricket'],
'bv': ['N/A'],
'bw': ['Football', 'Athletics', 'Netball'],
'by': ['Ice Hockey', 'Football', 'Handball'],
'bz': ['Cycling', 'Football', 'Basketball'],
'ca': ['Ice Hockey', 'Lacrosse', 'Canadian Football'],
'cc': ['N/A'],
'cd': ['Football', 'Basketball', 'Athletics'],
'cf': ['Football', 'Basketball', 'Athletics'],
'cg': ['Football', 'Basketball', 'Handball'],
'ch': ['Skiing', 'Ice Hockey', 'Football'],
'ci': ['Football', 'Basketball', 'Athletics'],
'ck': ['Rugby Union', 'Netball', 'Rugby League'],
'cl': ['Football', 'Tennis', 'Rodeo'],
'cm': ['Football', 'Athletics', 'Basketball'],
'cn': ['Table Tennis', 'Badminton', 'Basketball'],
'co': ['Cycling', 'Football', 'Baseball'],
'cr': ['Football', 'Surfing', 'Volleyball'],
'cu': ['Baseball', 'Boxing', 'Volleyball'],
'cv': ['Football', 'Basketball', 'Athletics'],
'cw': ['Baseball', 'Football', 'Volleyball'],
'cx': ['N/A'],
'cy': ['Football', 'Basketball', 'Volleyball'],
'cz': ['Ice Hockey', 'Football', 'Tennis'],
'de': ['Football', 'Handball', 'Basketball'],
'dj': ['Football', 'Basketball', 'Athletics'],
'dk': ['Football', 'Handball', 'Badminton'],
'dm': ['Cricket', 'Football', 'Athletics'],
'do': ['Baseball', 'Basketball', 'Volleyball'],
'dz': ['Football', 'Athletics', 'Handball'],
'ec': ['Football', 'Basketball', 'Volleyball'],
'ee': ['Basketball', 'Volleyball', 'Athletics'],
'eg': ['Football', 'Squash', 'Handball'],
'eh': ['Football', 'Athletics', 'Basketball'],
'er': ['Cycling', 'Athletics', 'Football'],
'es': ['Football', 'Basketball', 'Tennis'],
'et': ['Athletics', 'Football', 'Cycling'],
'fi': ['Ice Hockey', 'Athletics', 'Skiing'],
'fj': ['Rugby Union', 'Rugby League', 'Football'],
'fk': ['N/A'],
'fm': ['N/A'],
'fo': ['Football', 'Handball', 'Volleyball'],
'fr': ['Football', 'Tennis', 'Cycling'],
'ga': ['Football', 'Basketball', 'Athletics'],
'gb': ['Football', 'Rugby Union', 'Cricket'],
'gd': ['Cricket', 'Football', 'Athletics'],
'ge': ['Rugby Union', 'Football', 'Wrestling'],
'gf': ['Football', 'Cycling', 'Athletics'],
'gg': ['N/A'],
'gh': ['Football', 'Boxing', 'Athletics'],
'gi': ['Football', 'Cricket', 'Basketball'],
'gl': ['Handball', 'Football', 'Badminton'],
'gm': ['Wrestling', 'Football', 'Athletics'],
'gn': ['Football', 'Basketball', 'Athletics'],
'gp': ['Football', 'Cycling', 'Athletics'],
'gq': ['Football', 'Basketball', 'Athletics'],
'gr': ['Football', 'Basketball', 'Water Polo'],
'gs': ['N/A'],
'gt': ['Football', 'Futsal', 'Volleyball'],
'gu': ['American Football', 'Basketball', 'Baseball'],
'gw': ['Football', 'Basketball', 'Athletics'],
'gy': ['Cricket', 'Football', 'Basketball'],
'hk': ['Horse Racing', 'Football', 'Badminton'],
'hm': ['N/A'],
'hn': ['Football', 'Baseball', 'Basketball'],
'hr': ['Football', 'Handball', 'Basketball'],
'ht': ['Football', 'Basketball', 'Volleyball'],
'hu': ['Water Polo', 'Football', 'Handball'],
'id': ['Badminton', 'Football', 'Pencak Silat'],
'ie': ['Gaelic Games', 'Horse Racing', 'Rugby Union'],
'il': ['Football', 'Basketball', 'Judo'],
'im': ['Motorcycle Racing', 'Football', 'Rugby Union'],
'in': ['Cricket', 'Football', 'Badminton'],
'io': ['N/A'],
'iq': ['Football', 'Basketball', 'Weightlifting'],
'ir': ['Wrestling', 'Football', 'Volleyball'],
'is': ['Handball', 'Football', 'Basketball'],
'it': ['Football', 'Cycling', 'Volleyball'],
'je': ['N/A'],
'jm': ['Athletics', 'Cricket', 'Football'],
'jo': ['Football', 'Basketball', 'Taekwondo'],
'jp': ['Baseball', 'Football', 'Sumo Wrestling'],
'ke': ['Athletics', 'Rugby Union', 'Football'],
'kg': ['Wrestling', 'Football', 'Boxing'],
'kh': ['Football', 'Volleyball', 'Sepak Takraw'],
'ki': ['Weightlifting', 'Volleyball', 'Football'],
'km': ['Football', 'Basketball', 'Athletics'],
'kn': ['Cricket', 'Football', 'Athletics'],
'kp': ['Football', 'Basketball', 'Volleyball'],
'kr': ['Baseball', 'Football', 'Basketball'],
'kw': ['Football', 'Handball', 'Basketball'],
'ky': ['Cricket', 'Football', 'Athletics'],
'kz': ['Boxing', 'Cycling', 'Ice Hockey'],
'la': ['Muay Lao', 'Football', 'Volleyball'],
'lb': ['Football', 'Basketball', 'Rugby League'],
'lc': ['Cricket', 'Football', 'Athletics'],
'li': ['Football', 'Skiing', 'Alpine Skiing'],
'lk': ['Cricket', 'Rugby Union', 'Volleyball'],
'lr': ['Football', 'Basketball', 'Athletics'],
'ls': ['Football', 'Athletics', 'Netball'],
'lt': ['Basketball', 'Football', 'Athletics'],
'lu': ['Cycling', 'Football', 'Tennis'],
'lv': ['Ice Hockey', 'Basketball', 'Floorball'],
'ly': ['Football', 'Basketball', 'Volleyball'],
'ma': ['Football', 'Athletics', 'Boxing'],
'mc': ['Motorsports', 'Football', 'Basketball'],
'md': ['Football', 'Weightlifting', 'Judo'],
'me': ['Water Polo', 'Football', 'Basketball'],
'mf': ['N/A'],
'mg': ['Rugby Union', 'Football', 'Petanque'],
'mh': ['N/A'],
    'mk': ['Handball', 'Football', 'Basketball'],
    'ml': ['Football', 'Basketball', 'Athletics'],
    'mm': ['Football', 'Sepak Takraw', 'Volleyball'],
    'mn': ['Wrestling', 'Horse Racing', 'Archery'],
    'mo': ['N/A'],
    'mp': ['N/A'],
    'mq': ['Football', 'Cycling', 'Athletics'],
    'mr': ['Football', 'Athletics', 'Basketball'],
    'ms': ['Cricket', 'Football', 'Athletics'],
    'mt': ['Football', 'Water Polo', 'Basketball'],
    'mu': ['Football', 'Cycling', 'Athletics'],
    'mv': ['Football', 'Cricket', 'Basketball'],
    'mw': ['Football', 'Netball', 'Athletics'],
    'mx': ['Football', 'Boxing', 'Baseball'],
    'my': ['Badminton', 'Football', 'Bowling'],
    'mz': ['Football', 'Basketball', 'Athletics'],
    'na': ['Football', 'Rugby Union', 'Cricket'],
    'nc': ['Cricket', 'Football', 'Rugby Union'],
    'ne': ['Football', 'Basketball', 'Athletics'],
    'nf': ['N/A'],
    'ng': ['Football', 'Basketball', 'Athletics'],
    'ni': ['Baseball', 'Football', 'Boxing'],
    'nl': ['Football', 'Cycling', 'Field Hockey'],
    'no': ['Skiing', 'Football', 'Handball'],
    'np': ['Cricket', 'Football', 'Volleyball'],
    'nr': ['Weightlifting', 'Australian Rules Football', 'Athletics'],
    'nu': ['Archery', 'Football', 'Volleyball'],
    'nz': ['Rugby Union', 'Cricket', 'Netball'],
    'om': ['Football', 'Cricket', 'Camel Racing'],
    'pa': ['Baseball', 'Football', 'Boxing'],
    'pe': ['Football', 'Volleyball', 'Surfing'],
    'pf': ['Football', 'Va\'a', 'Athletics'],
    'pg': ['Rugby League', 'Rugby Union', 'Cricket'],
    'ph': ['Basketball', 'Boxing', 'Billiards'],
    'pk': ['Cricket', 'Field Hockey', 'Squash'],
    'pl': ['Football', 'Volleyball', 'Ski Jumping'],
    'pm': ['N/A'],
    'pn': ['N/A'],
    'pr': ['Baseball', 'Basketball', 'Boxing'],
    'ps': ['Football', 'Athletics', 'Basketball'],
    'pt': ['Football', 'Futsal', 'Roller Hockey'],
    'pw': ['Baseball', 'Basketball', 'Volleyball'],
    'py': ['Football', 'Volleyball', 'Basketball'],
    'qa': ['Football', 'Camel Racing', 'Handball'],
    're': ['Football', 'Cycling', 'Athletics'],
    'ro': ['Football', 'Handball', 'Tennis'],
    'rs': ['Football', 'Basketball', 'Tennis'],
    'ru': ['Ice Hockey', 'Football', 'Basketball'],
    'rw': ['Football', 'Basketball', 'Cycling'],
    'sa': ['Football', 'Camel Racing', 'Falconry'],
    'sb': ['Football', 'Rugby Union', 'Athletics'],
    'sc': ['Football', 'Athletics', 'Volleyball'],
    'sd': ['Football', 'Basketball', 'Athletics'],
    'se': ['Ice Hockey', 'Football', 'Handball'],
    'sg': ['Badminton', 'Table Tennis', 'Swimming'],
    'sh': ['Football', 'Cricket', 'Athletics'],
    'si': ['Ski Jumping', 'Alpine Skiing', 'Basketball'],
    'sj': ['N/A'],
    'sk': ['Ice Hockey', 'Football', 'Tennis'],
    'sl': ['Football', 'Basketball', 'Athletics'],
    'sm': ['Football', 'Basketball', 'Volleyball'],
    'sn': ['Wrestling', 'Football', 'Basketball'],
    'so': ['Football', 'Basketball', 'Athletics'],
    'sr': ['Football', 'Basketball', 'Volleyball'],
    'ss': ['Football', 'Basketball', 'Athletics'],
    'st': ['Football', 'Basketball', 'Athletics'],
    'sv': ['Football', 'Basketball', 'Surfing'],
    'sx': ['N/A'],
    'sy': ['Football', 'Basketball', 'Weightlifting'],
    'sz': ['Football', 'Netball', 'Athletics'],
    'tc': ['Cricket', 'Football', 'Athletics'],
    'td': ['Football', 'Basketball', 'Athletics'],
    'tf': ['N/A'],
    'tg': ['Football', 'Basketball', 'Athletics'],
    'th': ['Muay Thai', 'Football', 'Sepak Takraw'],
    'tj': ['Football', 'Wrestling', 'Judo'],
    'tk': ['N/A'],
    'tl': ['Football', 'Martial Arts', 'Volleyball'],
    'tm': ['Football', 'Cycling', 'Weightlifting'],
    'tn': ['Football', 'Handball', 'Basketball'],
    'to': ['Rugby Union', 'Football', 'Netball'],
    'tr': ['Football', 'Basketball', 'Volleyball'],
    'tt': ['Cricket', 'Football', 'Athletics'],
    'tv': ['Weightlifting', 'Volleyball', 'Football'],
    'tw': ['Baseball', 'Basketball', 'Badminton'],
    'tz': ['Football', 'Athletics', 'Netball'],
    'ua': ['Football', 'Boxing', 'Gymnastics'],
    'ug': ['Football', 'Athletics', 'Netball'],
    'uk': ['Football', 'Rugby Union', 'Cricket'],
    'um': ['N/A'],
    'us': ['American Football', 'Baseball', 'Basketball'],
    'uy': ['Football', 'Basketball', 'Rugby Union'],
    'uz': ['Football', 'Wrestling', 'Boxing'],
    'va': ['N/A'],
    'vc': ['Cricket', 'Football', 'Athletics'],
    've': ['Baseball', 'Football', 'Basketball'],
    'vg': ['Cricket', 'Football', 'Athletics'],
    'vi': ['American Football', 'Basketball', 'Baseball'],
    'vn': ['Football', 'Volleyball', 'Badminton'],
    'vu': ['Football', 'Volleyball', 'Athletics'],
    'wf': ['N/A'],
    'ws': ['Rugby Union', 'Netball', 'Volleyball'],
    'ye': ['Football', 'Athletics', 'Basketball'],
    'yt': ['N/A'],
    'za': ['Cricket', 'Rugby Union', 'Football'],
    'zm': ['Football', 'Athletics', 'Netball'],
    'zw': ['Cricket', 'Football', 'Rugby Union'],
    'xk': ['Football', 'Basketball', 'Handball']
}


wiki_language_codes = ['aa',
 'ab',
 'ace',
 'ady',
 'af',
 'ak',
 'als',
 'alt',
 'ami',
 'am',
 'ang',
 'ann',
 'anp',
 'an',
 'arc',
 'ar',
 'ary',
 'arz',
 'ast',
 'as',
 'atj',
 'avk',
 'av',
 'awa',
 'ay',
 'azb',
 'az',
 'ban',
 'bar',
 'ba',
 'bbc',
 'bcl',
 'bdr',
 'be',
 'bew',
 'bg',
 'bh',
 'bi',
 'bjn',
 'blk',
 'bm',
 'bn',
 'bo',
 'bpy',
 'br',
 'bs',
 'btm',
 'bug',
 'bxr',
 'ca',
 'cdo',
 'ceb',
 'ce',
 'cho',
 'chr',
 'ch',
 'chy',
 'ckb',
 'co',
 'crh',
 'cr',
 'csb',
 'cs',
 'cu',
 'cv',
 'cy',
 'dag',
 'da',
 'de',
 'dga',
 'din',
 'diq',
 'dk',
 'dsb',
 'dtp',
 'dty',
 'dv',
 'dz',
 'ee',
 'el',
 'eml',
 'en',
 'eo',
 'es',
 'et',
 'eu',
 'ext',
 'fat',
 'fa',
 'ff',
 'fi',
 'fj',
 'fon',
 'fo',
 'frp',
 'frr',
 'fr',
 'fur',
 'fy',
 'gag',
 'gan',
 'ga',
 'gcr',
 'gd',
 'glk',
 'gl',
 'gn',
 'gom',
 'gor',
 'got',
 'gpe',
 'guc',
 'gur',
 'gu',
 'guw',
 'gv',
 'hak',
 'ha',
 'haw',
 'he',
 'hif',
 'hi',
 'ho',
 'hr',
 'hsb',
 'ht',
 'hu',
 'hy',
 'hyw',
 'hz',
 'ia',
 'iba',
 'id',
 'ie',
 'igl',
 'ig',
 'ii',
 'ik',
 'ilo',
 'inh',
 'io',
 'is',
 'it',
 'iu',
 'jam',
 'ja',
 'jbo',
 'jv',
 'kaa',
 'kab',
 'ka',
 'kbd',
 'kbp',
 'kcg',
 'kge',
 'kg',
 'ki',
 'kj',
 'kk',
 'kl',
 'km',
 'kn',
 'koi',
 'ko',
 'krc',
 'kr',
 'ksh',
 'ks',
 'kus',
 'ku',
 'kv',
 'kw',
 'ky',
 'lad',
 'la',
 'lbe',
 'lb',
 'lez',
 'lfn',
 'lg',
 'lij',
 'li',
 'lld',
 'lmo',
 'ln',
 'lo',
 'lrc',
 'ltg',
 'lt',
 'lv',
 'mad',
 'mai',
 'mdf',
 'mg',
 'mhr',
 'mh',
 'min',
 'mi',
 'mk',
 'ml',
 'mni',
 'mn',
 'mnw',
 'mos',
 'mo',
 'mrj',
 'mr',
 'ms',
 'mt',
 'mus',
 'mwl',
 'myv',
 'my',
 'mzn',
 'nah',
 'nap',
 'na',
 'nds',
 'ne',
 'new',
 'ng',
 'nia',
 'nl',
 'nn',
 'nov',
 'no',
 'nqo',
 'nrm',
 'nr',
 'nso',
 'nv',
 'ny',
 'oc',
 'olo',
 'om',
 'or',
 'os',
 'pag',
 'pam',
 'pap',
 'pa',
 'pcd',
 'pcm',
 'pdc',
 'pfl',
 'pih',
 'pi',
 'pl',
 'pms',
 'pnb',
 'pnt',
 'ps',
 'pt',
 'pwn',
 'qu',
 'rm',
 'rmy',
 'rn',
 'ro',
 'rsk',
 'rue',
 'ru',
 'rw',
 'sah',
 'sat',
 'sa',
 'scn',
 'sco',
 'sc',
 'sd',
 'se',
 'sg',
 'shi',
 'shn',
 'sh',
 'si',
 'skr',
 'sk',
 'sl',
 'smn',
 'sm',
 'sn',
 'so',
 'sq',
 'srn',
 'sr',
 'ss',
 'stq',
 'st',
 'su',
 'sv',
 'sw',
 'szl',
 'szy',
 'ta',
 'tay',
 'tcy',
 'tdd',
 'ten',
 'tet',
 'te',
 'tg',
 'th',
 'ti',
 'tk',
 'tlh',
 'tl',
 'tly',
 'tn',
 'to',
 'tpi',
 'trv',
 'tr',
 'ts',
 'tt',
 'tum',
 'tw',
 'tyv',
 'ty',
 'udm',
 'ug',
 'uk',
 'ur',
 'uz',
 'vec',
 'vep',
 've',
 'vi',
 'vls',
 'vo',
 'war',
 'wa',
 'wo',
 'wuu',
 'xal',
 'xh',
 'xmf',
 'yi',
 'yo',
 'za',
 'zea',
 'zgh',
 'zh',
 'zu']


# language_code_country_codes = {}

# for (country_code, country_name) in countries.items():
# 	languages = babel.languages.get_territory_language_info(country_code)
# 	if len(languages) == 0:
# 		continue
# 	# top_language_code = sorted(languages.keys(), key=lambda language_code:languages[language_code]['population_percent'], reverse=True)[0]
# 	# language_code_country_codes.setdefault(top_language_code, []).append(country_code)
# 	for language_code in languages.keys():
# 		try:
# 			language = pycountry.languages.lookup(language_code)
# 			if language is not None and hasattr(language, 'alpha_2'):
# 				print(language)
# 				language_code_country_codes.setdefault(language.alpha_2, []).append(country_code)
# 		except LookupError:
# 			pass


# print(language_code_country_codes)

nginx_rules = []

for language_code in wiki_language_codes:
	

	nginx_rules += ['''
	location ^~ /{language_code}wiki {{
        root /mnt/wikimedia/dumps/;
        fancyindex_footer /res/geo/footer-{language_code}.html;
    }}
	'''.format(language_code=language_code)]

	footer_html = ['''
		</div>
	<hr>
	<div><img src="https://bringyour.com/res/images/URnetwork-logo-black-400-80.svg" width="200px" alt="URnetwork"></div>
	<div>Hosted by ''' 
	]

	country_codes = language_code_country_codes.get(language_code, [])
	for country_code in country_codes:
		# <a href="https://ur.io" target="_blank">VPN United States</a>
		# print('VPN {}'.format(countries[country_code]))
		country = countries[country_code]
		country_slug = re.sub(r'\s+', '-', country.lower())
		footer_html += [
		'''<a href="https://ur.io/how-to-get-a-vpn/vpn-access-in-{country_slug}" target="_blank">VPN {country}</a>
		'''.format(
			country_slug=country_slug,
			country=country)]
	footer_html += [
	'<a href="https://ur.io/ip" target="_blank">What&#39;s my IP</a>',
	'<a href="https://ur.io/ip" target="_blank">What&#39;s my latency</a>',
	'''URnetwork - all of the privacy and all of the fun.</div>
	''']

	for country_code in country_codes:
		country = countries[country_code]
		country_slug = re.sub(r'\s+', '-', country.lower())

		top_sports = country_code_top_sports[country_code]
		for sport in top_sports:
			footer_html += [
			'''<div><a href="https://ur.io/how-to-get-a-vpn/vpn-access-in-{country_slug}" target="_blank">VPN {country} {sport}</a></div>
			'''.format(
				country_slug=country_slug,
				country=country,
				sport=sport)]

	

	footer_html += [
	'''</body>
	</html>
	''']

	os.makedirs('build/res/geo', exist_ok=True)
	with open('build/res/geo/footer-{}.html'.format(language_code), 'w') as f:
		f.write(' '.join(footer_html))

os.makedirs('build', exist_ok=True)
with open('build/nginx-footer.conf', 'w') as f:
	f.write('\n'.join(nginx_rules))
