// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/urnetwork/whereami/landmarks"
	"github.com/urnetwork/whereami/myinfo"
)

func Index(info myinfo.MyInfo, expectedRTTs []landmarks.LandmarkAndRTT) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Your IP Information</title><script type=\"module\" src=\"/my-ip-widget.js\"></script><script type=\"module\" src=\"/my-ip-info.js\"></script></head><body class=\"bg-gray-100 flex justify-center items-center min-h-screen\"><div class=\"text-center min-w-96\"><my-ip-widget class=\"my-ip\" href=\"/ip\"></my-ip-widget></div><div class=\"text-center min-w-96\"><my-ip-info class=\"my-ip\"></my-ip-info></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
