export const contributors = [
    {
        id: 'brien',
        number: '01',
        name: 'Brien Colwell',
        role: 'Engineering',
        accent: 'pink',
        href: 'https://www.linkedin.com/in/briencolwell',
        platform: 'LinkedIn',
        image: '/team/brien-colwell.jpeg',
        bio: 'Engineering the network, protocol and products behind UR.',
        detail: 'Brien leads engineering at UR, from the protocol’s routing and verification systems to the applications built on top. He brings more than a decade of experience building mobile infrastructure at global scale.',
        focus: ['Protocol', 'Systems', 'Product'],
    },
    {
        id: 'ryan',
        number: '02',
        name: 'Ryan Mello',
        role: 'Developer',
        accent: 'burn',
        href: 'https://x.com/Ryanmello07',
        platform: 'X',
        image: '/team/ryan-mello.jpg',
        bio: 'Building and shipping the software that makes UR usable.',
        detail: 'Ryan leads development at UR, building across mobile, desktop, backend services and the infrastructure that supports them. His background spans game anti-cheat, Linux systems and production service administration.',
        focus: ['Development', 'Interfaces', 'Shipping'],
    },
    {
        id: 'jack',
        number: '03',
        name: 'Jack Ai-Leung',
        role: 'Commercialisation',
        accent: 'green',
        href: 'https://x.com/haitzu',
        platform: 'X',
        image: '/team/jack-ai-leung.jpg',
        bio: 'Partnerships and the path from protocol to market.',
        detail: 'Jack leads UR’s commercial work, connecting the protocol with investors and partners. His background spans private equity, token strategy and the commercialisation of open-source technology.',
        focus: ['Partnerships', 'Strategy', 'Market'],
    },
    {
        id: 'lemz',
        number: '04',
        name: 'Lemz',
        role: 'Growth',
        accent: 'blue',
        href: 'https://x.com/Lemz0x',
        platform: 'X',
        image: '/team/lemz.jpg',
        bio: 'Growth, community and making the network legible.',
        detail: 'Lemz leads growth at UR, connecting product, content, community and launch execution. His background spans marketing, community building, and research across web3.',
        focus: ['Growth', 'Community', 'Story'],
    },
];
