/**
 * Generates react/src/data/legal.js from docs/legal/{terms,privacy,vdp}.md
 * — the canonical legal documents for this site — so the legal pages render the
 * real documents on both renderers instead of placeholders.
 *
 * legal-md.mjs is a copy of mmm/ur.io/react/scripts/legal-md.mjs (the repos
 * build independently); if the converter grows, update both.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { legalMdToHtml, legalTitle, legalUpdated } from "./legal-md.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Each site keeps its own legal documents: ur.xyz's live here in the ur.xyz
// site, ur.io's in mmm/ur.io/docs/legal. Moved 2026-08-10 from the ur.io
// corpus (mmm/ur.io/docs/legal/ur.xyz) so the documents sit with the site
// that publishes them.
const DOCS = path.resolve(__dirname, "../docs/legal");
const OUT = path.resolve(__dirname, "../react/src/data/legal.js");

const DOC_KEYS = ["terms", "privacy", "vdp"];

const entries = DOC_KEYS.map((key) => {
  const md = readFileSync(path.join(DOCS, `${key}.md`), "utf8");
  const title = legalTitle(md);
  const updated = legalUpdated(md);
  const html = legalMdToHtml(md);
  if (html.length < 500) {
    console.error(`generate-legal: ${key}.md produced suspiciously little HTML — refusing`);
    process.exit(1);
  }
  return `  ${key}: {\n    title: ${JSON.stringify(title)},\n    updated: ${JSON.stringify(updated)},\n    html: ${JSON.stringify(html)},\n  },`;
});

writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-legal.mjs from docs/legal/*.md — do not edit.
export const LEGAL_DOCS = {
${entries.join("\n")}
};
`
);
console.log(`wrote ${OUT} (${DOC_KEYS.join(", ")})`);
