import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  DevicePhoneMobileIcon,
  GlobeAltIcon,
  UserIcon,
  UsersIcon,
} from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

const navigation = [
  {
    name: "Your Devices",
    href: "/devices",
    icon: DevicePhoneMobileIcon,
    current: true,
  },
  {
    name: "Friends and Family Devices",
    href: "/ffdevices",
    icon: UsersIcon,
    current: false,
  },
  { name: "Provide", href: "/provide", icon: GlobeAltIcon, current: false },
  { name: "Account", href: "/account", icon: UserIcon, current: false },
];

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(" ");
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full text-gray-900">
      <body className="h-full bg-white">
        <section id="sidebar" className="h-full fixed z-50 flex bg-teal-800  ">
          <div className="flex grow flex-col gap-y-5 overflow-y-auto bg-indigo-600 px-6 pb-2">
            <div className="flex h-16 shrink-0 items-center">
              <img
                className="h-8 w-auto"
                src="/bringyour-logo.webp"
                alt="Bringyour logo"
              />
            </div>
            <nav className="flex flex-1 flex-col mt-6">
              <ul role="list" className="flex flex-1 flex-col gap-y-7">
                <li>
                  <ul role="list" className="-mx-2 space-y-1">
                    {navigation.map((item) => (
                      <li key={item.name}>
                        <a
                          href={item.href}
                          className={classNames(
                            item.current
                              ? "bg-indigo-700 text-white"
                              : "text-indigo-200 hover:text-white hover:bg-indigo-700",
                            "group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold"
                          )}
                        >
                          <item.icon
                            className={classNames(
                              item.current
                                ? "text-white"
                                : "text-indigo-200 group-hover:text-white",
                              "h-6 w-6 shrink-0"
                            )}
                            aria-hidden="true"
                          />
                          {item.name}
                        </a>
                      </li>
                    ))}
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </section>
        <main className="min-h-full py-10 pl-72">{children}</main>
      </body>
    </html>
  );
}
