name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Packages
        run: cd app && npm i

      - name: Build
        run: cd app && npm run build

      - name: Lint
        run: cd app && npm run lint
